### ISSUE TITLE
implement StringToBaseModelConverter<T>.WriteJson() to support serialization

### ISSUE THREAD

**Issue by drch-** [paymill/paymill-net#19]
We are serializing request and response objects from our third party payment providers for logging and auditing purposes.

Models that use the [JsonConverter(StringToBaseModelConverter<T>)] attribute are not serializable via Json.NET as WriteJson() throws a not implemented exception.

**Comment by VMarinov1** [comment]
Hi @drch- , 
Could you send me an example, or JSON response ? 
Thank you

**Comment by drch-** [comment]
The following test throws a NotImplementedException()

        [TestMethod]
        public void TestPaymentSerialize()
        {
            var payment = ReadResult<Payment>("payment.json");
            var serialized = JsonConvert.SerializeObject(payment);
        }

**Comment by VMarinov1** [comment]
Hi @drch- I understand, you need Payment object as JSON ? I will fix it shortly.

**Comment by VMarinov1** [comment]
@drch- you will find the resolution in last commit. You can find you test in https://github.com/paymill/paymill-net/blob/master/UnitTest/Models/TestJsonDeserialization.cs#L99

**Comment by hydr** [comment]
Could you push a new nuget package for the recent changes?

**Comment by VMarinov1** [comment]
Hi @drch- ,
There is one more issue and I will upload it. Please use it from here if you are in a rush. I will upload the new version next week.

**Comment by VMarinov1** [comment]
Hi @drch- , version 3.0.2 is uploaded in Nuget.
