### ISSUE TITLE
Amount should be multiplied by 100

### ISSUE THREAD

**Issue by Alkaersig** [paymill/paymill-net#23]
This line:
                int amount = int.Parse(tbAmount.Text);

Should probably be changed into:
                int amount = int.Parse(tbAmount.Text) * 100;

When creating the token, the amount is multiplied by 100:
                amount_int: $('.amount').val() * 100,  // E.g. "15" for 0.15 Eur

As 1 (whatever currency) = 100. But when creating the transaction the amount is not multiplied so you only make a transaction for 1/100 of what is input in the amount field.

So to make the example complete, this should probably be aligned.

**Comment by VMarinov1** [comment]
Thank you @Alkaersig, I will fix it, this week,
