### ISSUE TITLE
Fix unit tests or remove them

### ISSUE THREAD

**Issue by SCullman** [paymill/paymill-net#25]
15 from 105 unit tests are currently failing:
UnitTest (2 tests) Failed 
  Net (10 tests) Failed 
    MSTest Class UnitTest.Net.TestPreauthorization (8 tests) Failed 
      MSTest Test UnitTest.Net.TestPreauthorization.ListOrderByFilterAmountGreaterThan Failed 
      MSTest Test UnitTest.Net.TestPreauthorization.ListOrderByFilterAmountLessThan Failed 
      MSTest Test UnitTest.Net.TestPreauthorization.RemovePreauthorization Failed 
    MSTest Class UnitTest.Net.TestRefundes (9 tests) Failed 
      MSTest Test UnitTest.Net.TestRefundes.RefundTransactionAndAmountAndDescrition Failed 
      MSTest Test UnitTest.Net.TestRefundes.RefundTransactionIdAndAmountAndDescrition Failed 
      MSTest Test UnitTest.Net.TestRefundes.RefundTransactionIdWithAmount Failed 
      MSTest Test UnitTest.Net.TestRefundes.RefundTransactionWithAmount Failed 
    MSTest Class UnitTest.Net.TestTransactions (16 tests) Failed 
      MSTest Test UnitTest.Net.TestTransactions.CreateTransactionWithPreauthorization Failed 
      MSTest Test UnitTest.Net.TestTransactions.CreateTransactionWithPreauthorizationAndDescription Failed 
    MSTest Class UnitTest.Net.TestWebhooks (9 tests) Failed 
      MSTest Test UnitTest.Net.TestWebhooks.CreateEmailWebhook Failed 
      MSTest Test UnitTest.Net.TestWebhooks.CreateURLWebhook Failed 
      MSTest Test UnitTest.Net.TestWebhooks.GetWebhook Failed 
      MSTest Test UnitTest.Net.TestWebhooks.GetWebhooks Failed 
      MSTest Test UnitTest.Net.TestWebhooks.RemoveWebhook Failed 
      MSTest Test UnitTest.Net.TestWebhooks.UpdateWebhook Failed

**Comment by VMarinov1** [comment]
Thank you @SCullman I will fix/update them.

**Comment by VMarinov1** [comment]
fixed in 121f0651a5886769b712103d161d29093ec68081
