### ISSUE TITLE
Missing SEPA Functionality

### ISSUE THREAD

**Issue by xan589** [paymill/paymill-net#28]
Hello,

currently there is no option for adding an SEPA payment object or an  debit payment.

**Comment by VMarinov1** [comment]
Hi @xan589 it will be added next week.

**Comment by xan589** [comment]
@VMarinov1 thank you!

**Comment by VMarinov1** [comment]
@xan589 please look at this: https://github.com/paymill/paymill-net/blob/master/PaymillWrapper/Models/Transaction.cs#L168
You can set SEPA mandate reference.
